feat: implement new dashboard navigation (#1397)
* Add size xsm (24px) to Avatar props
* Enable top level styling on Button component
* Added NextNavBar to root behind feature flag next_navbar
* Refactor login and register buttons inside NextNavBar
* Use tailwind container queries with mv- prefix
* Outsource NextNavBar to routes/__components.tsx
* Add NavBarMenu component and NavBarMenu.Opener to NextNavBar
* Implement close button in navbar menu
* Show NextNavBar on login, register, reset and auth/confirm when feature access is enabled
* Add Navbar to non app base routes on feature flag
* Refactored the non app base routes a little bit
* Footer only displayed on landing page with feature flag
* Made NextNavBar and NavBarMenu sticky top
* add overflow-auto-y
* NavBarMenu finished except all icons
* Build next routes for NavBarMenu Links
* Implement NavBarMenu only with searchParams and make it accessible and extendable from top level
* Add Icons and Avatars to NavBarMenu items
* Change depth of NavBarMenu
* Revert OverlayScrollbar package integration. Too much side effects
* Prevent scroll reset on topic items
* fix: wrong padding on TopicItems
* fix: close menu topics when top level item is visited
* Use old breakpoints on landing page to get a even state for refactoring all routes with the @container queries
* Use css to unfold navbarmenu and js to enable folding it automatically
* Add new LocaleSwitch variant "dark" and change "chevron-right" icon
* Style NextFooter
* Add i18n and refactor next routes and navbar routing
* Scroll to top button shouldnt overlay the footer on landing page
* Refactor all pages to @container queries
* Remove route error.tsx
* Make Filter work again without feature flag next_navbar
* fix: styling issues on nonAppBaseRoutes
* fix: change style of contact card on organization and profile detail only when ability next_navbar has access
* fix: modal on project detail not opening
* fix: result canvas of image cropper was shown in the document
* fix: TypeError zod.e2 is undefined when opening image cropper
* fix: value instead of defaultValue on uncontrolled hidden input
* fix: Client validation failed, getExtension() is not a function
* fix: React does not recognize the `initialError` prop on a DOM element.
* fix: preventScrollReset on search tabs
* fix: input props from Conform not spread correctly into the input elements
* fix: getExtension has no single source of truth
* fix: modal for editing images and documents on project settings attachments
* preventScrollReset on modals
* overflow hidden on modals
* Add filter vector script to seed database script
* fix: show more button on filter fieldset not working
* fix: form-label class not working with container queries
* fix: extended tailwind classes not working with container queries
* fix: mv-container-custom css-class not working with container queries, transformed it into utility styles
* fix: modal does not overlay navbar
* align next/fundings to new container queries
* move fundings to next/explore
* Remove mv-container-custom from tailwind.css as it was transformed to utility styles
* Link to existing pages from nextNavBarMenu if possible, else hide the menu item and add a TODO
* delete unused explore routes
* fix: modal root should be available without abuse_report feature access as its also used on different places (f.e. image upload, ...)
* fix: browser error missing key prop on <li>